### ISSUE TITLE
Defeat screen - cannot select mission

### ISSUE THREAD

**Issue by eliasmistler** [stefanhendriks/Dune-II---The-Maker#368] opened 2021-12-16 01:11 UTC
After being defeated in a campaign mission, I am not able to select an area on the strategy map, i.e. I am stuck.

**Comment by stefanhendriks** [comment] 2021-12-18 15:57
Can you tell me which campaign (which house) and which mission?

**Comment by stefanhendriks** [comment] 2021-12-18 15:58
This does remind me of #322 , which is fixed in the next version. Does it look like the same issue to you?

**Comment by eliasmistler** [comment] 2021-12-18 15:59
It was the Atreides campaign, and I believe it was mission 8

⁣Get BlueMail for Android ​

On 18 Dec 2021, 15:57, at 15:57, Stefan Hendriks ***@***.***> wrote:
>Can you tell me which campaign (which house) and which mission?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/stefanhendriks/Dune-II---The-Maker/issues/368#issuecomment-997222420
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by eliasmistler** [comment] 2021-12-18 16:00
Yes that's the same issue

⁣Get BlueMail for Android ​

On 18 Dec 2021, 15:58, at 15:58, Stefan Hendriks ***@***.***> wrote:
>This does remind me of #322 , which is fixed in the next version. Does
>it look like the same issue to you?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/stefanhendriks/Dune-II---The-Maker/issues/368#issuecomment-997222519
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by stefanhendriks** [comment] 2021-12-20 07:21
Closing this issue, as it is a duplicate of #322. (and it is fixed in the next version).

**Closed by stefanhendriks** 2021-12-20 07:21 UTC
Labels: investigating
